[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# RPC Endpoints
[rpc_endpoints]
arc-testnet = "https://rpc.testnet.arc.network"
arc-mainnet = "https://rpc.arc.network"
worldchain-sepolia = "https://worldchain-sepolia.g.alchemy.com/public"
worldchain-mainnet = "https://worldchain-mainnet.g.alchemy.com/public"
zerog-testnet = "https://evmrpc-testnet.0g.ai"

[etherscan]
arc-testnet = { key = "", url = "https://testnet.arcscan.app/api" }
worldchain-sepolia = { key = "", url = "https://worldchain-sepolia.explorer.alchemy.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
